### ISSUE TITLE
Key / Serial to HEX

### ISSUE THREAD

**Issue by MaxRei-dev** [chester4444/esp-multical21#14]
Hello Thank you for your great Work.
I Know it is a stubit Question but how do i convert the Serial / Key to HEX ?
Thank YOU

**Comment by runevad** [comment]
No real conversion is needed. 

//Example AES key: 
2041249E4AAB2AA052B06181156F07A2 is written as:
0x20, 0x41, 0x24, 0x9E, 0x4A, 0xAB, 0x2A, 0xA0, 0x52, 0xB0, 0x61, 0x81, 0x15, 0x6F, 0x07, 0xA2

//Example serial number: 76092980 is written as:
0x76, 0x09, 0x29, 0x80

**Comment by MaxRei-dev** [comment]
Thank you very mutch. I Was trying to convert it dec -> Hex ;-)
