### ISSUE TITLE
CRC Check

### ISSUE THREAD

**Issue by dkcsn** [chester4444/esp-multical21#4]
Hi Chester4444

Thank you for this great  work.
I was wondering if its possible for you to build in CRC check?
Some of the reading are wrong - in this example only the last reading shows all value correct.
So is it possible to create an error handler to detect this?

CurrentValue: 578.119 m3 - MonthStartValue: 386269.65 m3 - WaterTemp: 0 C - RoomTemp: 0 C
CurrentValue: 578.119 m3 - MonthStartValue: 386269.65 m3 - WaterTemp: 0 C - RoomTemp: 0 C
CurrentValue: 578.124 m3 - MonthStartValue: 2701252.1 m3 - WaterTemp: 6 C - RoomTemp: 23 C

**Comment by chester4444** [comment]
New version now features CRC check
