### ISSUE TITLE
Support for t1 protokol

### ISSUE THREAD

**Issue by babajun12** [chester4444/esp-multical21#8]
Hi,
currently I´m using wmbusmeter to read out a Diehl 171a meter (hydrus - t1) wich works perfekt. But I´d like to move this task to an ESP8266. Is it possible to implement the t1 protokol into your scetch?
Unfortunately my programming knowledge is to weak
Thx Gerhard

**Comment by CentauriDK** [comment]
I don't that such a meter so I am sadly not able to test it and implement that.

**Comment by chester4444** [comment]
Closed, no T1 here either
