### ISSUE TITLE
credentials - MQTT

### ISSUE THREAD

**Issue by babajun12** [chester4444/esp-multical21#9]
Hi,
I´d like to give it a try and found that the crentails.h file is needed. See example below.
Why are three SSIDs implemented?

credentails.h:

`#ifndef CREDENTIALS_H`
`#define CREDENTIALS_H`
`#define SSID1 "1st_ssid"`
`#define PW1 "password_1"`
`#define SSID2 "2nd_ssid"`
`#define PW2 "password_2"`
`#define SSID3 "3rd_ssid"`
`#define PW3 "password3"`
`#define MQTT1 "192.168.1.30"`
`#define MQTT2 "192.168.1.30"`
`#define MQTT3 "192.168.1.30"`
`#define W_SERIAL_NUMBER "meter_serial"`
`#define W_ENCRYPTION_KEY "insert_your_key_here"`
`#endif`

Is there a way to add user:password for MQTT authentication?

352 `Serial.println(credentials[cred][2]);`

Regards,
Gerhard

**Comment by runevad** [comment]
I have made a file in my fork with MQTT Credentials. 

https://github.com/runevad/esp-multical21
